import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex items-center justify-center">
        <div className="flex gap-10 items-center">
          <h1 className="text-white text-3xl font-mono">Supabase Hackathon</h1>
          <img
            src="/vectors/supabase.svg"
            alt="Supabase Logo"
            height={40}
            width={40}
          />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
